export const styledItem = {
  headStyle: {
    color: "#353448",
    fontFamily: "Poppins",
    letterSpacing: "0px",
    fontSize: "18px",
    fontWeight: "500",
  },
  dataStyle: {
    color: "#353448 !important",
    fontSize: "16px",
    fontFamily: "Poppins",
    textAlign: "left",
    letterSpacing: "0px",
  },
  linkStyle: {
    color: "#49C792",
    textDecorationColor: "#49C792",
    cursor: "pointer",
    fontSize: "16px",
    textAlign: "left",
    fontFamily: "Poppins",
  },
  tableCellStyle: { borderColor: "#FFFFFF" },
  parentGridStyle: {
    width: "100%",
    overflow: "hidden",
    marginTop: "16px",
    borderRadius: "6px",
    border: "1px solid #E6E6E6",
    display: "inline-flex",
    bgcolor: "#FFFFFF",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  reminderBoxStyle: {
    display: "inline-block",
    padding: "4px 20px",
    borderRadius: "4px",
    cursor: "pointer",
  },
  reminderBoxStyle1: {
    display: "inline-block",
    padding: "4px 12px",
    borderRadius: "4px",
    cursor: "pointer",
  },
  reminderTextStyle: {
    color: "#ffffff",
    textAlign: "left",
    fontFamily: "Poppins",
    letterSpacing: "0px",
    fontSize: "14px",
  },
  tablePagenationStyle: {
    background: "#ffffff",
    borderTop: "1px solid #E6E6E6",
  },
  tableContainerStyle: {
    height: "67.7vh",
    scrollbarWidth: "none",
    scrollBehavior: "smooth",
  },
  feedbackText: {
    fontFamily: "Poppins",
    fontSize: "20px",
    textAlign: "left",
    color: "#353448",
    fontWeight: "500",
  },
  filterBoxIcon: {
    ".MuiAvatar-img": { height: "16px", width: "16px" },
    backgroundColor: "#49C792",
    borderRadius: "4px",
    padding: "0px 4px",
    cursor: "pointer",
  },
  parentGridSignalStyle: {
    bgcolor: "#FFFFFF",
    border: "1px solid #E3E3E3",
    borderRadius: "4px",
    padding: "16px ",
    marginTop: "24px",
  },
  parentBoxSignalStyle: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headSignalStyle: {
    color: "#353448",
    fontSize: "16px",
    textAlign: "left",
    letterSpacing: "0px",
    fontFamily: "Poppins",
    fontWeight: "500",
  },
  paperSearchStyle: {
    border: "1px solid #CACACA",
    display: "flex",
    alignItems: "center",
    padding: "5px 10px",
    width: "310px",
  },
  searchIconStyle: { color: "#888888", width: "20px", height: "20px" },
  searchInputBarStyle: {
    fontSize: "14px",
    fontFamily: "Poppins",
    textAlign: "left",
    letterSpacing: "0px",
    ml: 1,
  },
  signalButtonStyle: {
    textAlign: "left",
    fontSize: "16px",
    fontFamily: "Poppins",
    textTransform: "none",
    fontWeight: "300",
    bgcolor: "#49C792",
    padding: "3px 40px",
    color: "#ffffff !important",
  },
  bodyActionIconStyle: {
    height: "28px",
    width: "28px",
    ".MuiAvatar-img": { height: "12px", width: "12px" },
    bgcolor: "#EEFBF6",
    cursor: "pointer",
  },
  tabsStyle: { background: "#F0F0F0", padding: "24px" },
  editContentHeading: {
    color: "#484759",
    display: "flex",
    columnGap: "2px",
    textAlign: "left",
    fontFamily: "Poppins",
    letterSpacing: "0px",
    fontSize: "12px",
  },
  editContentTextBox: {
    height: "120px",
    padding: "0px",
    fontSize: "14px",
    fontFamily: "Poppins",
    color: "#353448",
    textAlign: "left",
    letterSpacing: "0px",
  },
  editContentHeadingMust: { color: "#F44F5A" },
  editContentBox: { paddingBottom: "16px" },
  editContentGrid: { padding: "24px" },
};
